# [START runtime]
runtime: nodejs10, npm i
handlers:
- url: /http://rushilpatel.us
  static_files: dist/demo-app/index.html
  upload: dist/demo-app/index.html
- url: /http://rushilpatel.us
  static_dir: dist/demo-app
# [END runtime]