# [START runtime]
runtime: nodejs10
handlers:
- url: /http://rushilpatel.us
  static_files: dist/playground/index.html
  upload: dist/playground/index.html
- url: /http://rushilpatel.us
  static_dir: dist/playground
# [END runtime]