image: node:latest

cache: 
  paths: 
    - node_modules/

stages:
  - deploy
  environment:
    name: develop
  script:
    - npm install
    - npm run build
    - npm run deploy
  only: 
    - master